version: '3'
services:
  postgres:
    restart: unless-stopped
    build:
      context: .
      dockerfile: fin-d-mechs-postgres.Dockerfile
    environment:
      POSTGRES_USER: "gian"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "FindMechsDB"
    volumes:
      - ./FindMechsDB_PostgreSQL.sql:/docker-entrypoint-initdb.d/FindMechsDB_PostgreSQL.sql:ro
      - FindMechsDB:/var/lib/postgresql
    ports:
      - 5432:5432
  node:
    restart: on-failure
    build:
      context: .
      dockerfile: fin-d-mechs-node.Dockerfile
    environment:
      JWTSECRET: "novaorbis"
      POSTGRES_USER: "gian"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "FindMechsDB"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "postgres"
    ports:
      - 81:3000
volumes:
  FindMechsDB:
